AUTO_RIA_API_KEYS: 
  - 8s85MIseNcyqLNhDgRSTZBBgZ1GDKVC5WUQLr1BD
  - geD4Z8A5je8p3q03jXsjKbgC3VXAFHWfFaK65fYo
  - LcvnpjKw3XWMGIyQxPnQmgDsg3RE8MNsBnqCzB8R
BASE_URL: 'https://developers.ria.com'
PAGE_COUNT: 100
MAX_SCRAPPED: 100
synchronization_options: all