AUTO_RIA_API_KEYS: 
  - 8s85MIseNcyqLNhDgRSTZBBgZ1GDKVC5WUQLr1BD
  - geD4Z8A5je8p3q03jXsjKbgC3VXAFHWfFaK65fYo
  - LcvnpjKw3XWMGIyQxPnQmgDsg3RE8MNsBnqCzB8R
  - njij8hW7vp51luuU2y8dTknurRceF8FpQAIzgQuY
BASE_URL: 'https://developers.ria.com'
PAGE_COUNT: 100
MAX_SCRAPPED: 100
SYNCHRONIZATION_OPTIONS: marks
COUNT_REQUESTS_PER_HOUR: 30


# "Легкові"	1
# "Мото"	2
# "Водний транспорт"	3
# "Спецтехніка"	4
# "Причепи"	5
# "Вантажівки"	6
# "Автобуси"	7
# "Автобудинки"	8
# "Повітряний транспорт"	9
# "Сільгосптехніка"	10
MAIN_CATEGORY_FOR_SCRAPP: 1